import { useState, useEffect, useCallback, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
import { formatDate } from '../utils/helpers';
import './Alerts.css';

export default function Alerts() {
  const navigate = useNavigate();

  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [severityFilter, setSeverityFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [updatingId, setUpdatingId] = useState(null);
  const [toasts, setToasts] = useState([]);

  // Toast notification helper
  const showToast = useCallback((msg, type = 'success') => {
    const id = Date.now() + Math.random();
    setToasts((prev) => [...prev, { id, msg, type }]);
    setTimeout(() => {
      setToasts((prev) => prev.filter((t) => t.id !== id));
    }, 4000);
  }, []);

  useEffect(() => {
    fetchAlerts();
  }, []);

  const fetchAlerts = async () => {
    try {
      setLoading(true);
      const res = await api.get('/alerts');
      if (res.data && Array.isArray(res.data)) {
        setAlerts(res.data);
      } else {
        setAlerts([]);
      }
    } catch (err) {
      console.warn('[Alerts] Fetch error:', err.message);
      setAlerts([]);
    } finally {
      setLoading(false);
    }
  };

  // Update alert status
  const handleUpdateStatus = useCallback(async (alertId, newStatus) => {
    try {
      setUpdatingId(alertId);
      const res = await api.patch(`/alerts/${alertId}/status`, { status: newStatus });
      const updated = res.data;

      setAlerts((prev) =>
        prev.map((a) => (a._id === alertId ? { ...a, status: updated.status || newStatus } : a))
      );

      showToast(`Alert marked as ${newStatus === 'resolved' ? 'Resolved' : 'Active'}.`);
    } catch (err) {
      showToast('Could not update alert: ' + (err.response?.data?.message || err.message), 'warning');
    } finally {
      setUpdatingId(null);
    }
  }, [showToast]);

  // Delete alert
  const handleDelete = useCallback(async (alertId) => {
    if (!window.confirm('Delete this alert?')) return;

    try {
      setUpdatingId(alertId);
      await api.delete(`/alerts/${alertId}`);
      setAlerts((prev) => prev.filter((a) => a._id !== alertId));
      showToast('Alert deleted.', 'info');
    } catch (err) {
      showToast('Could not delete alert: ' + (err.response?.data?.message || err.message), 'warning');
    } finally {
      setUpdatingId(null);
    }
  }, [showToast]);

  // Create incident directly from alert
  const handleCreateIncident = useCallback(async (alert) => {
    try {
      setUpdatingId(alert._id);
      const res = await api.post('/incidents', { alertId: alert._id });
      if (res.data) {
        showToast(`Incident ${res.data.incidentId || ''} created from this alert!`, 'success');
        setAlerts((prev) =>
          prev.map((a) => (a._id === alert._id ? { ...a, status: 'investigating' } : a))
        );
      }
    } catch (err) {
      showToast('Could not create incident: ' + (err.response?.data?.message || err.message), 'warning');
    } finally {
      setUpdatingId(null);
    }
  }, [showToast]);

  // Filter alerts by search, status, and severity
  const filteredAlerts = useMemo(() => {
    return alerts.filter((alert) => {
      if (severityFilter !== 'all' && alert.severity !== severityFilter) return false;
      if (statusFilter === 'active' && alert.status === 'resolved') return false;
      if (statusFilter === 'resolved' && alert.status !== 'resolved') return false;

      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const matchesTitle = alert.title?.toLowerCase().includes(q);
        const matchesDesc = alert.description?.toLowerCase().includes(q);
        const matchesLog = alert.sourceLog?.originalName?.toLowerCase().includes(q);
        return matchesTitle || matchesDesc || matchesLog;
      }
      return true;
    });
  }, [alerts, severityFilter, statusFilter, searchQuery]);

  const totalCount = alerts.length;
  const activeCount = alerts.filter((a) => a.status !== 'resolved').length;
  const resolvedCount = alerts.filter((a) => a.status === 'resolved').length;

  return (
    <div className="alt-page-root">
      {/* Toast Notifications */}
      <div className="green-dash-toast-container">
        {toasts.map((t) => (
          <div key={t.id} className={`green-dash-toast ${t.type}`}>
            <span className="green-dash-toast-dot" />
            <span>{t.msg}</span>
          </div>
        ))}
      </div>

      <div className="alt-container">
        {/* Header Bar */}
        <header className="alt-header-bar">
          <div>
            <h1 className="alt-header-title">Alerts</h1>
            <p className="ml-page-sub">
              Manage anomaly alerts generated by the system
            </p>
          </div>

          <div className="alt-header-actions">
            <button
              className="alt-btn-secondary"
              onClick={() => navigate('/ml-analysis')}
              title="Go to ML Analysis"
            >
              <span>Analyze Log</span>
            </button>
          </div>
        </header>

        {/* 3 TOP EXISTING CONTAINERS */}
        <section className="lu-metric-row">
          <div className="lu-metric-card">
            <div className="lu-metric-meta">
              <span className="lu-metric-lbl">Total Alerts</span>
              <div className="lu-metric-val-wrap">
                <span className="lu-metric-num">{totalCount}</span>
                <span className="lu-metric-unit">alerts</span>
              </div>
            </div>
          </div>

          <div className="lu-metric-card">
            <div className="lu-metric-meta">
              <span className="lu-metric-lbl">Active Alerts</span>
              <div className="lu-metric-val-wrap">
                <span className="lu-metric-num">{activeCount}</span>
                <span className="lu-metric-unit">active</span>
              </div>
            </div>
          </div>

          <div className="lu-metric-card">
            <div className="lu-metric-meta">
              <span className="lu-metric-lbl">Resolved Alerts</span>
              <div className="lu-metric-val-wrap">
                <span className="lu-metric-num">{resolvedCount}</span>
                <span className="lu-metric-unit">resolved</span>
              </div>
            </div>
          </div>
        </section>

        {/* SEARCH / FILTER CONTAINER */}
        <section className="alt-toolbar-card" style={{ padding: '16px 20px', background: '#ffffff', borderRadius: '14px', border: '1px solid #e8f1ed', display: 'flex', flexWrap: 'wrap', gap: '16px', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ flex: '1', minWidth: '240px' }}>
            <input
              type="text"
              placeholder="Search alerts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{
                width: '100%',
                background: '#f4f8f6',
                border: '1px solid #c9dfd5',
                borderRadius: '10px',
                padding: '8px 14px',
                fontSize: '13px',
                color: '#0c3631',
                outline: 'none',
                boxSizing: 'border-box',
              }}
            />
          </div>

          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            <span style={{ fontSize: '12px', fontWeight: '700', color: '#526b65' }}>Status:</span>
            {['all', 'active', 'resolved'].map((stat) => (
              <button
                key={stat}
                className={`alt-chip-btn ${statusFilter === stat ? 'active' : ''}`}
                onClick={() => setStatusFilter(stat)}
                style={{
                  background: statusFilter === stat ? '#0c3631' : '#f4f8f6',
                  color: statusFilter === stat ? '#ffffff' : '#526b65',
                  border: '1px solid #c9dfd5',
                  borderRadius: '8px',
                  padding: '6px 12px',
                  fontSize: '11px',
                  fontWeight: '700',
                  cursor: 'pointer',
                  textTransform: 'uppercase',
                }}
              >
                {stat}
              </button>
            ))}
          </div>

          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            <span style={{ fontSize: '12px', fontWeight: '700', color: '#526b65' }}>Severity:</span>
            {['all', 'critical', 'high', 'medium', 'low'].map((sev) => (
              <button
                key={sev}
                className={`alt-chip-btn ${severityFilter === sev ? 'active' : ''}`}
                onClick={() => setSeverityFilter(sev)}
                style={{
                  background: severityFilter === sev ? '#0c3631' : '#f4f8f6',
                  color: severityFilter === sev ? '#ffffff' : '#526b65',
                  border: '1px solid #c9dfd5',
                  borderRadius: '8px',
                  padding: '6px 12px',
                  fontSize: '11px',
                  fontWeight: '700',
                  cursor: 'pointer',
                  textTransform: 'uppercase',
                }}
              >
                {sev}
              </button>
            ))}
          </div>
        </section>

        {/* ALERTS CONTAINER */}
        <section className="lu-card">
          <div className="lu-card-header" style={{ marginBottom: '16px' }}>
            <div>
              <h3>Alerts Feed ({filteredAlerts.length})</h3>
              <span className="lu-card-sub">Anomalies flagged during analysis</span>
            </div>
          </div>

          {loading ? (
            <div style={{ textAlign: 'center', padding: '36px 0', color: '#526b65' }}>
              <div className="ml-spinner" style={{ margin: '0 auto 12px auto' }} />
              <span>Loading alerts...</span>
            </div>
          ) : filteredAlerts.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '40px 0', color: '#839b95' }}>
              <div style={{ fontSize: '32px', marginBottom: '8px' }}>🛡️</div>
              <h4 style={{ margin: '0 0 6px 0', color: '#0c3631' }}>No alerts found</h4>
              <p style={{ margin: 0, fontSize: '13px' }}>
                No anomaly alerts match your filter criteria.
              </p>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
              {filteredAlerts.map((alert) => {
                const isResolved = alert.status === 'resolved';
                const statusLabel = isResolved ? 'Resolved' : 'Active';
                const scoreValue = alert.anomalyScore !== undefined && alert.anomalyScore !== null
                  ? Number(alert.anomalyScore).toFixed(3)
                  : '0.024';
                const sourceLogName = alert.sourceLog?.originalName || 'activity_log.log';
                const alertTitle = alert.title || 'Unusual Network Activity';
                const descriptionText = alert.description || 'Unusual activity was detected in the analyzed log.';
                const dateText = formatDate(alert.detectedAt || alert.createdAt);

                return (
                  <div
                    key={alert._id}
                    style={{
                      background: '#ffffff',
                      border: '1px solid #e8f1ed',
                      borderRadius: '12px',
                      padding: '18px 20px',
                      display: 'flex',
                      flexDirection: 'column',
                      gap: '8px',
                      boxShadow: '0 2px 6px rgba(12, 54, 49, 0.03)',
                    }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                      <div>
                        <div style={{ fontSize: '15px', fontWeight: '700', color: '#0c3631' }}>
                          Alert: {alertTitle}
                        </div>
                      </div>

                      <div style={{ display: 'flex', gap: '8px' }}>
                        {isResolved ? (
                          <button
                            className="web-btn-secondary"
                            onClick={() => handleUpdateStatus(alert._id, 'new')}
                            disabled={updatingId === alert._id}
                            style={{ padding: '4px 10px', fontSize: '11px' }}
                          >
                            Reopen
                          </button>
                        ) : (
                          <button
                            className="green-dash-btn-primary"
                            onClick={() => handleUpdateStatus(alert._id, 'resolved')}
                            disabled={updatingId === alert._id}
                            style={{ padding: '4px 12px', fontSize: '11px' }}
                          >
                            Mark Resolved
                          </button>
                        )}
                        <button
                          onClick={() => handleCreateIncident(alert)}
                          disabled={updatingId === alert._id}
                          title="Create an Incident from this alert"
                          style={{
                            background: '#0c3631',
                            color: '#00d68f',
                            border: '1px solid #144e47',
                            borderRadius: '6px',
                            padding: '4px 10px',
                            cursor: 'pointer',
                            fontSize: '11px',
                            fontWeight: '700',
                          }}
                        >
                          + Incident
                        </button>
                        <button
                          onClick={() => handleDelete(alert._id)}
                          title="Delete alert"
                          style={{
                            background: '#fff',
                            border: '1px solid #fecdd3',
                            color: '#e11d48',
                            borderRadius: '6px',
                            padding: '4px 8px',
                            cursor: 'pointer',
                            fontSize: '11px',
                          }}
                        >
                          Delete
                        </button>
                      </div>
                    </div>

                    <p style={{ margin: 0, fontSize: '13px', color: '#526b65', lineHeight: '1.4' }}>
                      <strong>Description:</strong> {descriptionText}
                    </p>

                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '16px', fontSize: '12px', color: '#526b65', marginTop: '4px' }}>
                      <span>
                        Source Log: <strong style={{ color: '#0c3631' }}>{sourceLogName}</strong>
                      </span>
                      <span>
                        Anomaly Score: <strong style={{ color: '#ea580c' }}>{scoreValue}</strong>
                      </span>
                      <span>
                        Status: <strong style={{ color: isResolved ? '#059669' : '#dc2626' }}>{statusLabel}</strong>
                      </span>
                      <span>
                        Date: {dateText}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
